title : Ivan Stabile
#logo : /assets/img/photo-portfolio.png
Location : Siena, Italy
Phone number : +39 334 916 3027
Email : stabile.ivan98@gmail.com
Linkedin : https://www.linkedin.com/in/ivanstabile98/
GitHub : https://github.com/ivanstb98
Kaggle : https://www.kaggle.com/ivanstabile
theme : jekyll-theme-minimal
